In [ ]:
# Notes
import numpy as np

# Make a 2x2 Numpy Array
create_zeros = np.zeros((2, 2))
print(create_zeros)

# Numpy Range Function
rangE = np.arange(5, 12) # Print from 5 through 11
print(rangE)

# Create random numbers ranging through numbers
rangE = np.random.randint(low=1, high=200, size=5)
print(rangE)

# Create random floats from 0.0 to 1.0
rangE = np.random.random(5)
print(rangE)

[[0. 0.]
 [0. 0.]]
[ 5  6  7  8  9 10 11]
[167 163  37  15  36]
[0.12567254 0.00998405 0.86937325 0.55561534 0.18716384]


In [ ]:
# Create a Linear Dataset
import numpy

feature = np.arange(1, 21) # Create an array ranging from 1 to 20
print(f"Feature: {feature}")

label = (feature*3) + 4 # An example linear would be y = (x*3) + 4
print(f"Label: {label}")

# Create Noise in the dataset, ranging from -2 to 2, 20 in exact for the labels
noise = (np.random.random([20]) * 4) - 2
print(f"Noise: {noise}")

# Add noise to the label
label = label + noise
print(f"Noised Label: {label}")

Feature: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Label: [ 7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]
Noise: [-0.82528847  1.42302578 -0.38571574 -0.92147852  1.620258    0.57917003
 -0.05887463 -0.47060443  0.21725401 -1.94129094  1.90026207  0.28415629
 -1.52926449  0.46485804 -1.0536667  -0.84529     1.69414074 -0.19142096
 -1.64264032 -1.25351656]
Noised Label: [ 6.17471153 11.42302578 12.61428426 15.07852148 20.620258   22.57917003
 24.94112537 27.52939557 31.21725401 32.05870906 38.90026207 40.28415629
 41.47073551 46.46485804 47.9463333  51.15471    56.69414074 57.80857904
 59.35735968 62.74648344]
